server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native
    include: env
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/local-config-repo
#          search-locations: file://${user.home}/local-config-repo
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh